### ISSUE TITLE
implicit declaration of function 'DOLPHIN_DEED'

### ISSUE THREAD

**Issue by iehgit** [xMasterX/all-the-plugins#3]
When I compile apps from the sources in the source code zip, I get the following warning for a lot of apps:

```
applications_user/flipper-dcf77/dcf77_app.c:350:5: warning: implicit declaration of function 'DOLPHIN_DEED' [-Wimplicit-function-declaration]
  350 |     DOLPHIN_DEED(DolphinDeedPluginGameStart);
      |     ^~~~~~~~~~~~

```

**Comment by iehgit** [comment]
And those apps do not start, but give tho following message:
Error Load failed found unsatisfied imports

**Comment by iehgit** [comment]
This did help:
find applications_user -type f -exec sed -i 's/DOLPHIN_DEED/dolphin_deed/g' {} +

**Comment by xMasterX** [comment]
Use dev branch! I already updated and fixed this
