### ISSUE TITLE
[Flipper_Catalog] apps_data files are missing for Barcode_app

### ISSUE THREAD

**Issue by theblackhole** [xMasterX/all-the-plugins#6]
Hello,

I don't know if the issue is on your side or if it is an issue on the catalog side so I will create an issue for both.

Linked issue: https://github.com/flipperdevices/flipper-application-catalog/issues/47

TLDR: it seems like required app_data files are missing when installing apps from the Hub/Catalog 

Details :
I have an issue with the [barcode_app](https://lab.flipper.net/apps/barcode_app) installed with the android app via the Hub/Catalog: when I try to load a Code 128 barcode, it says "Missing encoding table".
After reading the [installation instructions on the original github repository](https://github.com/Kingal1337/flipper-barcode-generator#installing) I found that it needs encoding table files in a `apps_data/barcode_data` folder.
This folder is missing on my Flipper Zero:
![image](https://github.com/xMasterX/all-the-plugins/assets/7818904/201283b2-b1d9-4a79-8839-e3ab51cc99c7)
The issue disappeared after I added the missing folder and files manually:
![image](https://github.com/xMasterX/all-the-plugins/assets/7818904/dbc8c9ac-14d4-4e8d-912a-6c8e46542077)

**Comment by xMasterX** [comment]
Files are not packed into app itself, and cannot be shipped separately, catalog doesnt allow to add external assets 
I will remake this app to have them all packed into this app, a bit later

**Comment by xMasterX** [comment]
Files are not packed into app itself, and cannot be shipped separately, catalog doesnt allow to add external assets 
I will remake this app to have them all packed into this app, a bit later

**Comment by RogueMaster** [comment]
Or better yet, Flipper Devices gives a way to pack files for the SD with the app install...

**Comment by xMasterX** [comment]
> Or better yet, Flipper Devices gives a way to pack files for the SD with the app install...

This is exactly what i said

**Comment by xMasterX** [comment]
Fixed, will be updated in catalog soon
